import { Navigation, Pagination, Scrollbar } from "swiper";import { Swiper, SwiperSlide } from "swiper/react";import "swiper/css";import "swiper/css/navigation";import "swiper/css/pagination";import "swiper/css/scrollbar";import React from "react";import InnerHTML from "dangerously-set-html-content";export default function IM80018() {function importAll(r) {let images = {};r.keys().forEach((item, index) => {images[item.replace("./", "")] = r(item);});return images;}const imgs = importAll(require.context(`../../../assets/imoveis/IM80018`,false,/\.(png|jpe?g|svg|webp)$/));const googleMaps = `<div class="mapouter"><div class="gmap_canvas"><iframe src="https://maps.google.com/maps?q=Avenida%20Morumbi,%208503%20-%20%20São%20Paulo%20/%20SP%20Apt/Sala:%20%20-%20%20Bloco:%20-%20Andar:%20&amp;t=&amp;z=18&amp;ie=UTF8&amp;iwloc=&amp;output=embed" id="gmap_canvas" frameborder="0" scrolling="no" style="width: 100%; height: 400px;"></iframe><style>.mapouter{position:relative;text-align:right;height:400px;width:100%;}</style><a href="https://googlemapsiframegenerator.com" style="display:none">Google Maps Iframe Generator - Free Html Embed Code</a><style>.gmap_canvas{overflow:hidden;background:none!important;height:400px;width:100%;}</style></div></div>`;return (<><div className="container"><div className=""><div className=""><div className=""><div className="swiper_container"><Swiper modules={[Navigation, Pagination, Scrollbar]} spaceBetween={50} slidesPerView={1} navigation pagination={{ clickable: true }} scrollbar={{ draggable: true }}>{Object.entries(imgs).map((t, k) => (<SwiperSlide> <div key={k[0]}className="swiper_slide"> <img src={t[1]} alt="image do imovel" /></div></SwiperSlide>))}</Swiper></div><div className="imoveis_desp"><hr /><h1>Loja em Santo Amaro com 440m²</h1><p>Avenida Morumbi, 8503 -  São Paulo / SP Apt/Sala:  -  Bloco: - Andar: </p><p>Finalidade: Aluguel</p><p>Valor da Locação: R$ 35.000,00</p><p>Valor da Venda: R$ 0,00</p><hr /><h2>Descrição</h2><p>Espaço comercial em excelente localização na Av. Morumbi, uma região formada pelos pontos mais cobiçados da cidade, onde você e sua empresa encontrarão segurança, conforto e comodidade a 2 minutos da estação Brooklin do metrô e da Av Santo Amaro, a 5 minutos da Chucri Zaidan e Morumbi Shopping. 
São 440m2 distribuídos em vão principal, mezanino integrado, hall de entrada, sala de apoio, toaletes, cozinha equipada, cozinha de apoio, vestuários e lavanderia.
Acabamento de primeira linha, com detalhes arquitetônicos em madeira maciça, granito e mármore, louças e metais deca nos toaletes que são 3 (social feminino, social masculino e para portadores de necessidades especiais), iluminação cênica, climatização com máquinas de ar condicionado central, sistema de segurança interno com câmeras, sonorização ambiente, cozinha totalmente equipada para uso industrial, ponto para gerador com capacidade até 100KVAs, tela de 50?, paisagismo externo e mobiliário completo para uso de Buffet ou restaurante:

05 módulos revestidos em courvim marrom
01 Sofá de 04 lugares marrom
03 mesas tipo bistro
04 mesas de apoio
02 Poltronas marrons 
03 Bambus mosso em cachepos de madeira de 4m de altura
25 mesas de 1,45 e 230 cadeiras de ferro cor cafe modelo tiffany

IPTU:.R$3.094,00</p><hr /><InnerHTML className="center" html={googleMaps}></InnerHTML></div></div></div></div></div></>);}